### ISSUE TITLE
[Suggestion] Swipe-to-delete in UITableView not working; optionally exclude gesture directions

### ISSUE THREAD

**Issue by Flitskikker** [sascha/DrawerController#43] opened 2016-01-08 17:14 UTC
Hi,

I have been using DrawerController in one of my Swift applications, in which I'm mainly using UITableViews. I am only using a left navigation view and the center view.

I stumbled upon an issue when I wanted to add swipe-to-delete functionality to my table. I noticed it was very difficult (or almost impossible) to trigger the swipe-to-delete option. I figured the drawer must have been causing this; probably a conflicting gesture listener. To verify this, I disabled the drawer, and the swipe-to-delete option was working perfectly.

I found issue reports for the original MMDrawerController, but not this version. @ShreeshGarg posted a code snippet that should fix the issue, so I tried to port it over:
https://github.com/mutualmobile/MMDrawerController/issues/207

I used this code and came up with the following that worked for me. I added it to the "UIGestureRecognizerDelegate" mark on line 1418.

```swift
public func gestureRecognizer(gestureRecognizer: UIGestureRecognizer, shouldRecognizeSimultaneouslyWithGestureRecognizer otherGestureRecognizer: UIGestureRecognizer) -> Bool {
    if let panGestureRecognizer = otherGestureRecognizer as? UIPanGestureRecognizer {
        if panGestureRecognizer.velocityInView(panGestureRecognizer.view).x < 0 {
            return true
        }
    }
    
    return false
}
```

Now swiping to the left works to reveal the Delete button.
It doesn't work perfectly yet (sometimes it gets in a state where you can scroll and pan simultaneously) and probably it only works correctly when you're only using a left menu and center view, so hopefully you can implement or know of a better solution to exclude gesture listening in a certain direction.

In the meantime, I hope people who encounter the same issue will find the above code snippet useful.

Thanks!

**Comment by maltebaumann** [comment] 2016-01-08 17:31
Hi, this is a quite general problem caused by the drawer controller. Your code works for your specific situation (only left VC, swipe-to-delete only), but in general the controls would need to be very granular. For example a user may want to close the swipe-menu (multiple buttons behind one cell, e.g. Mail app) after opening it. In that case you would also need to handle the other direction.

The DrawerController offers the openDrawerGestureMask property that allows to control, which gestures are recognised for opening the drawer controller. You can limit the swipeable area to the navigationbar or disable swipes completely. By doing so, the left drawer is only accessible via a menu button or by swiping the navigation bar and all swipe gestures within the center drawer controller work as expected. We suggest using this functionality, because its a more stable solution. But of course, if your solution fits someones needs, your code might come in handy ;)

I'll close this issue, as the current implementation offers a way around the issue and excluding gesture directions would need to be very granular and might lead to unexpected behaviour.

**Closed by maltebaumann** 2016-01-08 17:31 UTC

**Comment by Flitskikker** [comment] 2016-01-08 23:21
Thanks for your clarification!
